return {
    [0] = "Main",
    [1] = "Sub",
    [2] = "Range",
    [3] = "Ammo",
    [4] = "Head",
    [5] = "Body",
    [6] = "Hands",
    [7] = "Legs",
    [8] = "Feet",
    [9] = "Neck",
    [10] = "Waist",
    [11] = "Left Ear",
    [12] = "Right Ear",
    [13] = "Left Ring",
    [14] = "Right Ring",
    [15] = "Back",
}